### ISSUE TITLE
Description text does not wrap

### ISSUE THREAD

**Issue by jellyton255** [jellyton255/fivem-docs#1]
For some longer descriptions, the text does not wrap in the flex.

http://fivemdocs.jellyton.me/docs/natives/task/0x9B53BB6E8943AF53

**Comment by mafewtm** [comment]
I looked at this and it seems all that you'd have to do to get it to wrap properly is something like `white-space: pre-wrap;` which, if it was just `<Text>` that would be fine but you seem to have picked and chosen which natives use react-markdown. I'm not sure what the reason for that was but yea.

**Comment by mafewtm** [comment]
Descriptions seem to be fixed as of the latest updates you pushed. This can now be closed

**Comment by jellyton255** [comment]
Fixed: https://github.com/jellyton69/fivem-docs-mantine/commit/aaefd71c42c30451eaa147f6272a16e786aba199
